[tool.poetry]
name = "zelensky-speech-fetcher"
version = "0.1.0"
description = ""
authors = ["Slava Medvediev <slava.medvedev@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10.16"
requests = "^2.32.3"
pandas = "^2.2.3"
datasets = "^3.2.0"
huggingface-hub = "^0.27.1"
selenium = "^4.27.1"
transformers = "^4.50.0"
torch = "^2.6.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
