[tool.poetry]
name = "president-speech-fetch"
version = "0.1.0"
description = ""
authors = ["Slava Medvediev <slava.medvedev@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
requests = "^2.31.0"
lxml = "^4.9.3"
pandas = "^2.1.3"
cssselect = "^1.2.0"
datasets = "^2.14.6"
huggingface-hub = "^0.19.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
