[tool.poetry]
name = "zelensky-speech-fetcher"
version = "0.1.0"
description = ""
authors = ["Slava Medvediev <slava.medvedev@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10.12"
requests = "^2.32.0"
pandas = "^2.2.0"
datasets = "^2.16.1"
huggingface-hub = "^0.20.3"
selenium = "^4.15.2"
transformers = "^4.38.0"
torch = "^2.1.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
