[tool.poetry]
name = "zelensky-speech-fetcher"
version = "0.1.0"
description = ""
authors = ["Slava Medvediev <slava.medvedev@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10.16"
requests = "^2.32.4"
pandas = "^2.2.3"
datasets = "^3.2.0"
huggingface-hub = "^0.33.2"
selenium = "^4.34.0"
transformers = "^4.53.0"
torch = "^2.7.1"
poetry-core = "^2.1.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
