[tool.poetry]
name = "zelensky-speech-fetcher"
version = "0.1.0"
description = ""
authors = ["Slava Medvediev <slava.medvedev@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10.12"
requests = "^2.32.3"
pandas = "^2.2.2"
datasets = "^2.19.1"
huggingface-hub = "^0.23.2"
selenium = "^4.21.0"
transformers = "^4.41.2"
torch = "^2.3.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
