name: Fetch latest speeches from president.gov.ua and push them to the HuggingFace

on:
  schedule:
    - cron:  '0 0 * * *'
  workflow_dispatch:

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.8'
          cache: 'poetry'

      - name: Fetch and update speeches
        run: |
          poetry install --no-root
          source $(poetry env info --path)/bin/activate
          huggingface-cli login --token ${{ secrets.HF_TOKEN }} --add-to-git-credential
          python ./main.py

      - name: Commit and push latest speech timestamp
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Auto-update of last_speech_timestamp.txt" || exit 0
          git push
