name: Fetch latest speeches from president.gov.ua and push them to the HuggingFace

on:
  schedule:
    - cron: '20 23 * * *'
  workflow_dispatch:

env:
  HF_HOME: "./.huggignface"

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Check Chrome version
        run: google-chrome --version

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10.16'
          cache: 'poetry'

      - name: Fetch and update speeches
        uses: nick-fields/retry@v3
        with:
          max_attempts: 3
          timeout_minutes: 4
          command: |
            poetry install --no-root
            source $(poetry env info --path)/bin/activate
            hf auth login --token ${{ secrets.HF_TOKEN }}
            python ./src/z_scrap/main.py

      - name: Upload debug artifacts (if any)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: debug-output
          path: src/z_scrap/debug_output/
          if-no-files-found: ignore
          retention-days: 7

      - name: Commit and push latest speech timestamp
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add last_speech_timestamp_*.txt
          git commit -m "Auto-update of last_speech_timestamp_*.txt" || exit 0
          git push
