name: Fetch latest speeches from president.gov.ua and push them to the HuggingFace

on:
  schedule:
    - cron:  '0 0 * * *'
  workflow_dispatch:

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.8'
          cache: 'poetry'

      - name: Set poetry env variable
        run: echo "POETRY_ENV_PATH=$(poetry env info --path)" >> $GITHUB_ENV

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ${{ env.POETRY_ENV_PATH }}/lib
          key: ${{ runner.os }}-pip-${{ hashFiles('**/poetry.lock') }}

      - name: Activate Python environment and login to Huggingface
        run: |
          poetry install --no-root
          source $(poetry env info --path)/bin/activate
          huggingface-cli login --token ${{ secrets.HF_TOKEN }} --add-to-git-credential

      - name: Fetch and update speeches
        run: |
          source $(poetry env info --path)/bin/activate
          python ./main.py

      - name: Commit and push latest speech timestamp
        run: |
          git diff --name-only --exit-code origin/main -- last_speech_timestamp.txt
          if [ $? -eq 1 ]; then
            git config user.name github-actions
            git config user.email github-actions@github.com
            git add last_speech_timestamp.txt
            git commit -m "Auto-update of last_speech_timestamp.txt"
            git push
          else
            echo "No changes in last_speech_timestamp.txt"
          fi
